function functie(R, C, A, A0, min, max)
    % Creez fereastra principală pentru afisare
    Fig = figure('Name', 'Filtru Trece Sus', ... % Setez titlul ferestrei
                 'Units', 'normalized', ... % Dimensiuni relative la ecran
                 'Position', [0.1, 0.1, 0.75, 0.75], ... % Poziția și mărimea ferestrei
                 'Color', [0.678, 0.847, 0.902], ... % Setez culoarea fundalului
                 'NumberTitle', 'off'); % Elimin numărul implicit din titlu

    % Valorile standardizate pentru R și C
    valori_R = [10, 20, 50, 100, 200, 500, 1000, 2000, 5000, 10000];
    valori_C = [1e-12, 1e-10, 1e-8, 1e-7, 1e-6, 1e-5, 1e-4, 1e-3, 1e-2, 1e-1];

    % Grup pentru "Date Intrare" - inputurile utilizatorului
    DateIn = uibuttongroup('Visible', 'on', ...
                           'BackgroundColor', [0.6, 0.847, 0.902], ...
                           'ForegroundColor', 'black', ...
                           'Title', 'Date Intrare', ...
                           'FontSize', 10, ...
                           'TitlePosition', 'centertop', ...
                           'Position', [0.03, 0.65, 0.3, 0.3]); 

    % Slider pentru R
    uicontrol('Style', 'Text', ...
              'Units', 'Normalized', ...
              'Position', [0.05, 0.8, 0.25, 0.1], ...
              'Parent', DateIn, ...
              'String', ' R (Ω)');
    slider_R = uicontrol('Style', 'slider', ...
                         'Units', 'Normalized', ...
                         'Position', [0.35, 0.8, 0.45, 0.1], ...
                         'Parent', DateIn, ...
                         'Min', 1, 'Max', 10, ...
                         'Value', find(valori_R == R), ...
                         'SliderStep', [1/9, 1/9], ...
                         'Callback', @(src, ~) actualizare_valori('R', valori_R, round(src.Value)));
    caseta_R = uicontrol('Style', 'edit', ...
                         'Units', 'Normalized', ...
                         'Position', [0.8, 0.8, 0.15, 0.1], ...
                         'Parent', DateIn, ...
                         'String', num2str(R), ...
                         'Enable', 'inactive');

    % Slider pentru C
    uicontrol('Style', 'Text', ...
              'Units', 'Normalized', ...
              'Position', [0.05, 0.65, 0.25, 0.1], ...
              'Parent', DateIn, ...
              'String', ' C (F)');
    slider_C = uicontrol('Style', 'slider', ...
                         'Units', 'Normalized', ...
                         'Position', [0.35, 0.65, 0.45, 0.1], ...
                         'Parent', DateIn, ...
                         'Min', 1, 'Max', 10, ...
                         'Value', find(valori_C == C), ...
                         'SliderStep', [1/9, 1/9], ...
                         'Callback', @(src, ~) actualizare_valori('C', valori_C, round(src.Value)));
    caseta_C = uicontrol('Style', 'edit', ...
                         'Units', 'Normalized', ...
                         'Position', [0.8, 0.65, 0.15, 0.1], ...
                         'Parent', DateIn, ...
                         'String', num2str(C), ...
                         'Enable', 'inactive');


    % Funcția de actualizare a valorilor R și C
    function actualizare_valori(parametru, valori, index)
        if strcmp(parametru, 'R')
            R = valori(index);
            set(caseta_R, 'String', num2str(R));
        elseif strcmp(parametru, 'C')
            C = valori(index);
            set(caseta_C, 'String', num2str(C));
        end
        close;
        functie(R, C, A, A0, min, max);
    end



     % Elemente pentru A
    uicontrol('Style', 'Text', ... % Eticheta amplitudinii
              'Units', 'Normalized', ...
              'Position', [0.05, 0.5, 0.25, 0.1], ...
              'Parent', DateIn, ...
              'String', ' A '); 
    uicontrol('Style', 'Edit', ... % Camp de editare a amplitudinii
              'Units', 'Normalized', ...
              'Position', [0.35, 0.5, 0.45, 0.1], ...
              'Parent', DateIn, ...
              'String', A, ...
              'Callback', 'A=str2num(get(gco,''String''));close;functie(R, C, A, A0, min, max);');
    uicontrol('Style', 'Text', ...  % Unitate de masura pentru A
              'Units', 'Normalized', ...
              'Position', [0.8, 0.5, 0.15, 0.1], ...
              'Parent', DateIn, ...
              'String', ' V');

    % Elemente pentru Decada minima
    uicontrol('Style', 'Text', ... % Eticheta pentru Decada minima
              'Units', 'Normalized', ...
              'Position', [0.05, 0.35, 0.25, 0.1], ...
              'Parent', DateIn, ...
              'String', ' Decada Min');
    uicontrol('Style', 'Edit', ... % Camp de editare pentru decada minima
              'Units', 'Normalized', ...
              'Position', [0.35, 0.35, 0.45, 0.1], ...
              'Parent', DateIn, ...
              'String', min, ...
              'Callback', 'min=str2num(get(gco,''String''));close;functie(R, C, A, A0, min, max);');
    uicontrol('Style', 'Text', ...  % Unitate pentru decade
              'Units', 'Normalized', ...
              'Position', [0.8, 0.35, 0.15, 0.1], ...
              'Parent', DateIn, ...
              'String', ' decade ');

    % Elemente pentru Decada Max
    uicontrol('Style', 'Text', ... % Eticheta pentru Decada maxima
              'Units', 'Normalized', ...
              'Position', [0.05, 0.2, 0.25, 0.1], ...
              'Parent', DateIn, ...
              'String', ' Decada Max');
    uicontrol('Style', 'Edit', ...  % Camp de editare pentru Decada maxima
              'Units', 'Normalized', ...
              'Position', [0.35, 0.2, 0.45, 0.1], ...
              'Parent', DateIn, ...
              'String', max, ...
              'Callback', 'max=str2num(get(gco,''String''));close;functie(R, C, A, A0, min, max);');
    uicontrol('Style', 'Text', ... % Unitate pentru decade
              'Units', 'Normalized', ...
              'Position', [0.8, 0.2, 0.15, 0.1], ...
              'Parent', DateIn, ...
              'String', ' decade ');

    % Checkbox pentru componenta continuă A0
    uicontrol('Style', 'Checkbox', ... 
              'Units', 'Normalized', ...
              'Position', [0.05, 0.05, 0.9, 0.1], ...
              'Parent', DateIn, ...
              'String', 'Adaugă componenta continuă A0', ...
              'Value', A0 > 0, ...
              'Callback', 'A0=get(gco,''Value'');close;functie(R, C, A, A0, min, max);');
        
        % Buton pentru Reset
    uicontrol('Style', 'PushButton', ...
              'Units', 'Normalized', ...
              'Position', [0.73, 0.87, 0.15, 0.05], ...
              'String', 'Reset', ...
              'FontSize', 10, ...
              'Callback', 'close; ProiectFTS');

    % Buton pentru Exit
    uicontrol('Style', 'PushButton', ...
              'Units', 'Normalized', ...
              'Position', [0.9, 0.87, 0.08, 0.05], ...
              'String', 'Exit', ...
              'FontSize', 10, ...
              'Callback', 'close all;');



    % Apelul functiiei "calcule" pentru a obtine valorile necesare
    [tau, omega0, f0, defaz] = calcule(R, C);

    %Grup pentru "Calcule" - pentru a afisa calculele
    Calc = uibuttongroup('Visible', 'on', ...
                         'BackgroundColor', [0.6, 0.847, 0.902], ...
                         'ForegroundColor', 'black', ...
                         'Title', 'Calcule', ...
                         'FontSize', 10, ...
                         'TitlePosition', 'centertop', ...
                         'Position', [0.03 0.35 0.3 0.3]);

    % Afisam rezultatele calculelor
    uicontrol('Style', 'Text', ... %eticheta a constantei de timp(tau)
              'Units', 'Normalized', ...
              'Position', [0.03, 0.75, 0.3, 0.2], ...
              'Parent', Calc, ...
              'String', ' 𝜏');     
    uicontrol('Style', 'Text', ... %valoarea constantei de timp
              'Units', 'Normalized', ...
              'Position', [0.33, 0.75, 0.3, 0.2], ...
              'Parent', Calc, ...
              'String', num2str(tau)); 
    uicontrol('Style', 'Text', ... %unitatea pentru constanta de timp
              'Units', 'Normalized', ...
              'Position', [0.63, 0.75, 0.3, 0.2], ...
              'Parent', Calc, ...
              'String', ' s ');

    uicontrol('Style', 'Text', ...  %eticheta a pulsatiei
              'Units', 'Normalized', ...
              'Position', [0.03, 0.55, 0.3, 0.2], ...
              'Parent', Calc, ...
              'String', ' ω₀'); 
    uicontrol('Style', 'Text', ... %valoarea pulsatiei
              'Units', 'Normalized', ...
              'Position', [0.33, 0.55, 0.3, 0.2], ...
              'Parent', Calc, ...
              'String', num2str(omega0)); 
    uicontrol('Style', 'Text', ...  %unitate pentru pulsatie
              'Units', 'Normalized', ...
              'Position', [0.63, 0.55, 0.3, 0.2], ...
              'Parent', Calc, ...
              'String', ' rad/s ');

    uicontrol('Style', 'Text', ...  %eticheta a frecventei de taiere(f0)
              'Units', 'Normalized', ...
              'Position', [0.03, 0.35, 0.3, 0.2], ...
              'Parent', Calc, ...
              'String', ' f₀');     
    uicontrol('Style', 'Text', ...  %valoarea frecventei de taiere
              'Units', 'Normalized', ...
              'Position', [0.33, 0.35, 0.3, 0.2], ...
              'Parent', Calc, ...
              'String', num2str(f0)); 
    uicontrol('Style', 'Text', ...  %unitate pentru frecventa de taiere
              'Units', 'Normalized', ...
              'Position', [0.63, 0.35, 0.3, 0.2], ...
              'Parent', Calc, ...
              'String', ' Hz ');

    uicontrol('Style', 'Text', ...  %eticheta a defazajului
              'Units', 'Normalized', ...
              'Position', [0.03, 0.14, 0.3, 0.2], ...
              'Parent', Calc, ...
              'String', ' Defazaj');  

    uicontrol('Style', 'Text', ... %valoarea defazajului
              'Units', 'Normalized', ...
              'Position', [0.33, 0.14, 0.3, 0.2], ...
              'Parent', Calc, ...
              'String', num2str(defaz));  
    uicontrol('Style', 'Text', ... %unitate pentru defazaj
              'Units', 'Normalized', ...
              'Position', [0.63, 0.14, 0.3, 0.2], ...
              'Parent', Calc, ...
              'String', ' grade ');

    Xc = 1 / (2 * pi * f0 * C);%reactanta capacitiva la frecventa de taiere
    frec = f0; % frecvenaa de taiere este f0
    t = linspace(0, 1, 1000); % definirea timpului pentru semnale

    Vin = A * sin(2 * pi * frec * t) + A0; % semnalul de intrare(contine A0)
    Vout = A * (R / (sqrt(Xc^2 + R^2))) * sin(2 * pi * frec * t + deg2rad(defaz)) + A0; %semnalul de iesire
    
    % Grafic pentru Vin & Vout in timp
    subplot('Position', [0.05 0.06 0.6 0.25]);
    plot(t, Vin, t, Vout);
    grid on;
    legend('Vin', 'Vout');
    xlabel('timp [s]', 'FontSize', 12, 'FontWeight', 'b'); 
    ylabel('Vin/Vout', 'FontSize', 12, 'FontWeight', 'b'); 



% Calculul pentru diagramele Bode
f = logspace(min, max, 500); % Frecvente pe o scară logaritmica
omega = 2 * pi * f;         % Pulsatia 
H = (1j * omega * R * C) ./ (1 + 1j * omega * R * C); % Functia de transfer

% Modulul (in dB) si faza (in grade)
Modul = 20 * log10(abs(H));
Faza = angle(H) * (180 / pi);

% Creez subploturi pentru diagramele Bode
subplot('Position', [0.4 0.45 0.25 0.3]); % Diagrama Modul
semilogx(f, Modul, 'b', 'LineWidth', 1.5);%modulul functiei de transfer
hold on;
semilogx(f0, 20*log10(abs((1j*2*pi*f0*R*C)/(1+1j*2*pi*f0*R*C))), 'ro', 'MarkerSize', 4, 'MarkerFaceColor', 'k');%punct pentru f0
hold off;
grid on;
title('Diagrama Modulului');
xlabel('Frecvența [Hz]');
ylabel('|H(j\omega)| [dB]');

subplot('Position', [0.72 0.45 0.25 0.3]); % Diagrama Faza
semilogx(f, Faza, 'r', 'LineWidth', 1.5);%faza functiei de transfer
hold on;
semilogx(f0, angle((1j*2*pi*f0*R*C)/(1+1j*2*pi*f0*R*C))*(180/pi), 'ro', 'MarkerSize', 4, 'MarkerFaceColor', 'k');% punct pentru f0
hold off;
grid on;
title('Diagrama Fazei');
xlabel('Frecvența [Hz]');
ylabel('\angle H(j\omega) [grade]');
 

% Adăugare buton "Salvează Date"
uicontrol('Style', 'pushbutton', 'String', 'Salvează Date', ...
    'Position', [800, 50, 120, 30], ... % Ajustează poziția după GUI
    'BackgroundColor', [0.6, 1, 0.6], ...
    'FontSize', 10, ...
    'Callback', @salveazaDate);

function salveazaDate(hObject, ~)
    % Obține datele din figura principală
    fig = ancestor(hObject, 'figure');
    dateIntrare = getappdata(fig, 'dateIntrare');
    dateIesire = getappdata(fig, 'dateIesire');

    % Verificare dacă există date de salvat
    if isempty(dateIntrare) || isempty(dateIesire)
        msgbox('Nu există date de intrare sau ieșire pentru salvare!', 'Eroare', 'error');
        return;
    end

    % Numele fișierului
    filename = 'date_salvate.txt';

    % Scrierea datelor în fișier
    try
        fid = fopen(filename, 'w');
        fprintf(fid, 'Date de intrare:\n');
        fprintf(fid, 'R: %g\nC: %g\nA: %g\nA0: %g\nmin: %g\nmax: %g\n', ...
                dateIntrare.R, dateIntrare.C, dateIntrare.A, dateIntrare.A0, dateIntrare.min, dateIntrare.max);

        fprintf(fid, '\nDate de ieșire:\n');
        fprintf(fid, 'tau: %g\nomega0: %g\nf0: %g\ndefaz: %g\n', ...
                dateIesire.tau, dateIesire.omega0, dateIesire.f0, dateIesire.defaz);
        fclose(fid);

        msgbox(['Datele au fost salvate cu succes în fișierul: ', filename], 'Succes');
    catch ME
        msgbox(['A apărut o eroare la salvarea datelor: ', ME.message], 'Eroare', 'error');
        if exist('fid', 'var') && fid > 0
            fclose(fid);
        end
    end
end

% Salvare date intrare
dateIntrare = struct('R', R, 'C', C, 'A', A, 'A0', A0, 'min', min, 'max', max);
setappdata(Fig, 'dateIntrare', dateIntrare);

% Salvare date ieșire
dateIesire = struct('tau', tau, 'omega0', omega0, 'f0', f0, 'defaz', defaz, ...
                    'Vin', Vin, 'Vout', Vout, 'Modul', Modul, 'Faza', Faza);
setappdata(Fig, 'dateIesire', dateIesire);



end

