% Pagina de start
% Proiect Filtru Trece Sus --- Baciu Petru Rares

close all 

Fig=figure('Name','Proiect',... 
           'Units','normalized',...
           'Position',[0.1 0.1 0.7 0.7],...
           'NumberTitle','off');
       
%axa pentru fundal
axes('Position', [0 0 1 1]); %acopera intreaga figura
x = imread('fundal.jpg');
imshow(x); %afiseaza fundalul
axis off;

%Axa pentru imaginea din centru
axes('Position', [0.23 0.35 0.55 0.5]); % pozitioneaza in centrul paginii
y = imread('schemaFTS.jpg');
imshow(y); % afiseaza imaginea
axis off;

uicontrol('Style','text',... 
'Units','normalized',...
'Position',[0.3 0.8 0.379 0.1],...
'BackgroundColor','w',...
'Fontname','Calibri',...
'FontSize',24,...
'string','Filtru trece-sus - RC');
      
uicontrol('style','pushbutton',...
          'Units','normalized',...
          'Position',[0.35 0.2 0.3 0.11],...
          'Backgroundcolor','y',...
          'string',' Proiect ',...
          'FontName','Calibri',...
          'FontSize',20,...
          'Callback','ProiectFTS');

uicontrol('style','pushbutton',...
          'Units','normalized',...
          'Position',[0.1 0.1 0.18 0.1],...
          'string',' Prezentare ',...
          'FontName','Calibri',...
          'FontSize',20,...
          'Backgroundcolor','y',...
          'Callback','open (''Prezentare.pdf'')');

uicontrol('style','pushbutton',...
          'Units','normalized',...
          'Position',[0.72 0.1 0.18 0.1],...
          'string',' Documentație ',...
          'FontName','Calibri',...
          'FontSize',20,...
          'Backgroundcolor','y',...
          'Callback','open (''Documentatie.docx'')');




